export default [
  {
    imageId: 1,
    imageTitle: 'testImage',
    itemImage: 'https://fec-yelp-images.s3-us-west-1.amazonaws.com/food1.jpg',
    imageCategory: 'food',
    imageDescription: 'yummy dish',
    imageUploadDate: '2020-05-01T07:00:00.000Z',
    userId: 1,
    restaurantId: 2,
  },
  {
    imageId: 2,
    imageTitle: 'testImage1',
    itemImage: 'https://fec-yelp-images.s3-us-west-1.amazonaws.com/food2.jpg',
    imageCategory: 'decor',
    imageDescription: 'nice environment',
    imageUploadDate: '2020-05-01T07:00:00.000Z',
    userId: 1,
    restaurantId: 2,
  },
  {
    imageId: 3,
    imageTitle: 'testImage2',
    itemImage: 'https://fec-yelp-images.s3-us-west-1.amazonaws.com/food3.jpg',
    imageCategory: 'food',
    imageDescription: 'super good',
    imageUploadDate: '2020-05-01T07:00:00.000Z',
    userId: 1,
    restaurantId: 2,
  },
];
